services:
  - type: web
    name: kvs-rental-backend
    runtime: node
    plan: free
    rootDir: kvs_rental_shop-main/backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL_CA
        sync: false

  - type: web
    name: kvs-rental-frontend
    runtime: static
    rootDir: kvs_rental_shop-main/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://kvs-rental-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html